### PR TITLE
Huge Update

### PR DESCRIPTION
**Pull request by SwissCorePy**
Sorry for the huge commit. 

Fixed Tons of bugs, added zoom support, added folders.

Just play the game and take a look yourself :)

### CODE REVIEW

**Comment by AOx0** [comment]
Great, I'm going to take a look at it.

**Comment by AOx0** [comment]
With the advanced folder feature the Advanced Chips option in settings gets obsolete. I'm going to remove the "Advanced Chips option"

**Comment by SwissCorePy** [comment]
Great! Thanks for merging. I will also continue work on this, when I have enough time again. :)

there are still some unfixed bugs
* input/output groups are sliding around weired while changing scale.
* chips with unconnected input pins are not working after packageing. (eg. if you pachage an NOT gate and only connect the output, the out but of the parent chip should always be on. but it is off. coulb be fixed using a invisible pseudo input pin which is logically connected to all unconnected input pins)
* bad performance in large projects. (even on my pc with i9-9900K @ 4.8GHz and RX 5700XT )

I will make a complete list of bugs i found soon.

**Comment by SwissCorePy** [comment]
And sorry again, i planned to make a clean and complete update includeing the mentioned bug fixes. but then i had much less time to work on that project. 
and after 2 or 3 months without working on it, i decided to publish the current version.

**Pull request merged**
