### PR TITLE
converted HDD to 16bit Flashable EEPROM

### PR DESCRIPTION
**Pull request by HannesGitH**
- HDD was a weird name i propose RAM/EEPROM/flash/memory (i chose EEPROM)
- this chip doesnt use spi as most eeprom/flash chips but 16 address and 16 data lines
   - this was chosen because spi functionality can be added ontop with the normal editor 
- 65536 addresses with 2 bytes each -> 128kiB
- **flashable with a .bin file**
   - when building a full custom computer chip in DLS you might want to run programms
   - this chip can be progamm(&data) storage that can come from a custom external compiler/assembler
   - the assembler creates a .bin file which can be flashed onto this EEPROM chip

### CODE REVIEW

**Comment by HannesGitH** [comment]
the EEPROM can be dynamically sized in the unity editor 
it might make sense to give this functionality to the user (can choose address and data bus sizes when adding a new eeprom)

**Comment by HannesGitH** [comment]
i didnt know about the decoder but it might make sense do directly include them in the eeprom s.t. only one line for address, data-in, data-out would be needed each

**Comment by HannesGitH** [comment]
eeprom

**Comment by crispeeweevile** [comment]
In what way was "HDD" a "weird name? I'm curious to hear what you have to say, because it has legit meaning, and is somewhat accurate to the current functionality.

**Comment by crispeeweevile** [comment]
> the EEPROM can be dynamically sized in the unity editor it might make sense to give this functionality to the user (can choose address and data bus sizes when adding a new eeprom)

I actually think this change could be pretty neat, but I think it would _probably_ be difficult actually implement said feature, as it _may_ require a rewrite for what happens when selecting a chip

**Comment by HannesGitH** [comment]
> In what way was "HDD" a "weird name? I'm curious to hear what you have to say, because it has legit meaning, and is somewhat accurate to the current functionality.

well, hdd beeing an acronym for hard disk drive is just not the best fit imo, since there is no disk
also when building circuits you rarely have a full hard drive as a storage medium, but use small flash storage chips like eeproms

but i'm open to other opinions :)

**Comment by crispeeweevile** [comment]
> > In what way was "HDD" a "weird name? I'm curious to hear what you have to say, because it has legit meaning, and is somewhat accurate to the current functionality.
> 
> well, hdd beeing an acronym for hard disk drive is just not the best fit imo, since there is no disk also when building circuits you rarely have a full hard drive as a storage medium, but use small flash storage chips like eeproms
> 
> but i'm open to other opinions :)

Alrighty, I actually agree to a certain extent, as technically EEPROM is more accurate, but also consider that EEPROM is over 2x as long a name, meaning that the chip would take more space on the X axis, this may not be an issue for you, but personally I like to stuff as much into as small a space as possible, I actually usually "remake" all the encoders and decoders to give them different names such as "04BE" (4 bit Encoder)

Regarding your suggestion of flashing said chip, I've got a note from my dad (he's actually pretty interested in the game) that the idea of an assembler/compiler is very high level, and doesn't really make sense for the game.

Also update with EEPROM, my dad says that EEPROM can only be reprogrammed in a special device, and once you've programmed it, it becomes ROM (Read Only Memory) which makes it confusing from a teaching perspective


Edit: added a whole new paragraph so I'm not spamming comments

**Comment by HannesGitH** [comment]
> Alrighty, I actually agree to a certain extent, as technically EEPROM is more accurate, but also consider that EEPROM is over 2x as long a name, meaning that the chip would take more space on the X axis, this may not be an issue for you, but personally I like to stuff as much into as small a space as possible, I actually usually "remake" all the encoders and decoders to give them different names such as "04BE" (4 bit Encoder)

i somewhat agree on the x-axis problem (hdd was called "hard disk" though when beeing placed for some reason :D) but i think 6 letters isnt to bad, considering we got that scale slider under options

>Regarding your suggestion of flashing said chip, I've got a note from my dad (he's actually pretty interested in the game) that the idea of an assembler/compiler is very high level, and doesn't really make sense for the game.

yeah the assembler wouldnt be part of the game, but ultimately you might come to the point where you build a whole cpu and look for a way to programm it (maybe with your own ISA).  i think having that possibility would be quite neat :)

> Also update with EEPROM, my dad says that EEPROM can only be reprogrammed in a special device, and once you've programmed it, it becomes ROM (Read Only Memory) which makes it confusing from a teaching perspective

no that's not correct, but its true that in a physical world you wouldnt want to rewrite it too often (as it is the case with a hdd), maybe flash would be a more fitting name?

**Comment by HannesGitH** [comment]
> > the EEPROM can be dynamically sized in the unity editor it might make sense to give this functionality to the user (can choose address and data bus sizes when adding a new eeprom)
> 
> I actually think this change could be pretty neat, but I think it would _probably_ be difficult actually implement said feature, as it _may_ require a rewrite for what happens when selecting a chip

that shouldnt be to hard i might have a look at it in the future

**Comment by HannesGitH** [comment]
Oh, i just noticed the old hdd had the same storage between multiple 'worlds' i removed that because when placing a second hdd it inherits the state from the last updated one, and when you close and reload the game all hdds have the same state of the one that was last updated

but i left this feature behind a flag in the unity editor

i propose adding a toggle and an id-field to the context-menu of the chip (where you currently load and store the .bin) 
s.t. a syncing behaviour can be archieved by which all chips that have this toggle on and the same id, have the same storage contents (also between 'worlds') 
To do that one would need to add the id field and in pass it through `SaveSystem.SaveEEPROMContents(contents);` and append that id to the eeprom savestate filename.

to have multiple eeproms with the same id in the same 'world' would need some extra work though, maybe sharing the same contents reference

**Comment by Paxol** [comment]
Hello to everyone. I forked this branch and I want to do something to improve this memory chip. I don't have much time to work on this but I want to try implementing something...

For now, I fixed the loading of custom chips that has this EEPROM inside. The loading crashed when it was creating the pins, caused by the pins arrays not being initialized.
I added a "metadata" field to saved chips so that any chips that need to save more data can do so and the EEPROM can save the number of pins to it.

I also want to implement the saving of the memory content to the disk. I think to give any memory chip a GUID, then if the memory is non-volatile, save the content to a file (maybe a file inside "projectDir/memories/{GUID}.bin").

As you may have guessed I would like to implement different types of memory
- persistent read-only (like ROM)
- persistent r/w (like EEPROM)
- volatile (like RAM)

You can track my work here: https://github.com/Paxol/Digital-Logic-Sim-CE/pull/1

Any suggestion is appreciated 😊

**Comment by HannesGitH** [comment]
> I also want to implement the saving of the memory content to the disk. I think to give any memory chip a GUID, then if the memory is non-volatile, save the content to a file (maybe a file inside "projectDir/memories/{GUID}.bin").

as far as i remember, loading and storing data contents as binaries is already in this branch :)

but glad i could motivate you 😇

**Comment by Paxol** [comment]
> loading and storing data contents as binaries is already in this branch :)

Yes, but I couldn't place 2 different EEPROMs with different memory, the bytes array for the memory content is static, so all EEPROMs are pointing to the same memory.

I want that every memory chip to be indipendent from other ones

**Comment by crispeeweevile** [comment]
> 

If I recall, part of the point was for them to point to the same information, allowing the user to save memory and move it between things

Perhaps you could implement a UI to change what memory it points to, and also allow the user to name that memory (so we know what each thing is)

**Comment by Paxol** [comment]
I don't understand why the pins that ends with 0 are the most significant bits. In every computer architecture lesson that I followed it was the opposite, A0 LSB and (assuming 16 bit numbers) A15 MSB.

This was very confusing to me and I changed the labels of the pins as follows
image



I'm also a bit surprised to see hexadecimal numbers in the pin count but I can live with this.

**Comment by Paxol** [comment]
Separate memories are implemented if anyone wants to check it out on https://github.com/Paxol/Digital-Logic-Sim-CE/pull/1.

Each EEPROM has a string ID, and all the memories are stored in a static dictionary, so if a memory chip is needed twice there is no waste of real pc RAM.

I think the next step is the menu where you can change the EEPROM id, as well as change the address and data sizes.

**Comment by HannesGitH** [comment]
> I don't understand why the pins that ends with 0 are the most significant bits. In every computer architecture lesson that I followed it was the opposite, A0 LSB and (assuming 16 bit numbers) A15 MSB.

my computer architecture lessons were some time ago, so sorry for mislabeling ;)

but shouldnt make that much of a difference tbh, since the chip itself defines nothing in regards to msb/lsb, given the same address the DO pins always have the same value you've put in. whats the msb is decided by the alu then.

**Comment by Paxol** [comment]
> but shouldnt make that much of a difference tbh

Yes, it's just a mental thing, I changed it so it's clear when with imported .bin files and the binary number showed by the grouped inputs match up.

**Comment by pudy248** [comment]
This doesn't work with the chip scaling at the moment. Should not be merged until that's fixed.

**Comment by pudy248** [comment]
Also, if you load a bin file smaller than the size of `contents`, since it overwrites the array directly, it shrinks contents and you get a bunch of index out of bounds errors

**Comment by HannesGitH** [comment]
> This doesn't work with the chip scaling at the moment. Should not be merged until that's fixed.

in hindsight i also woder why i opted for 16bit data/bus sizes ..
but the scaling can be easily configured (in the top left i think, but idk but theres definitley a scaling menu somewhere)

**Comment by HannesGitH** [comment]
> Also, if you load a bin file smaller than the size of `contents`, since it overwrites the array directly, it shrinks contents and you get a bunch of index out of bounds errors

good spot
can't remember what i coded though but sounds like a very easy fix

---
edit ah i see you already fixed that, well done!

**Comment by HannesGitH** [comment]
closed as covered by #73

**Pull request closed without merging**
