### PR TITLE
Add 32bit bus parts, extra bus features for IO pins, less harsh colors.

### LINKED ISSUE #55: Be compliant with Sebastian's community project guidelines
We are missing some of this [points](https://github.com/SebLague/Misc-Project-Info/blob/main/Digital-Logic-Sim/Fork%20Guidelines.md)

>  If you've created a fork of the Digital Logic Sim project, and plan on distributing it, please follow these guidelines:
> 
> 1. In the project settings, change the Company Name to something other than "SebastianLague".
> 2. Do not write save files into the same location as the official version (changing the company name will do this by default).
> 3. The project must be free to download (accepting donations is fine), and the source code must be available.
> 4. There should be some indication in the main menu that it's not the official version.
> 
> Thank you!

### LINKED ISSUE #60: Wires should be disconnected from IO pins when their bus type changes.
Title. Currently, wires stay connected, making connections between different pin types and generally causing issues. This should be trivial to fix.

### LINKED ISSUE #61: Edited chips do not load IO pin wire type correctly.
IO pins for viewed chips are always Simple, regardless of what the actual chip has. Loaded chips in the chip selector still load correctly, it's only during viewing and resaving that issues arise.

Pins can be changed back to their correct values before updating designs to preserve correctness, but resaving chips with invalid wire connections is possible.

### LINKED ISSUE #62: Allow direct pin bus modification
Tbh, Im not really comfortable with the fact that you have to decode a bus pin to be able to modify it
Cant there be a binary array panel on each bus pin menu that we can modify, (and a binary array panel on output pins, unmodifiable)? that would really help.

### PR DESCRIPTION
**Pull request by pudy248**
As it stands, using busses is quite difficult, since IO pins that are anything other than 1 bit cannot be edited or read without a decoder. This PR adds the ability to click on bus input pins and input a value to set the bus as, and all bus IO pins display their value when it isn't 0. 

32 bit encoders and decoders were mysteriously absent from the builtin chips, so those have also been added.

Also made pin/wire colors check if the state is greater than 0 instead of just equal to 1, since busses > 1 showed as off. Darkened the red ON color and significantly darkened the bus ON color since white text over it was almost unreadable and it was rather bright anyhow.

I had to do some funky stuff to make Git work on my machine, so let me know if I forgot to add a file to the commit and something seems off. Sufficiently large numbers inputted to busses end up significantly outside the text boxes, but if this weren't the case, the text would be too small to read.

### CODE REVIEW

**Comment by pudy248** [comment]
A future PR to add a global option to switch bus readouts/edits to be signed would be a good idea, but my development time is somewhat restricted right now.

**Comment by pudy248** [comment]
Now includes several bug fixes, and changes company name and project title to better follow SebLague community guidelines. Decided to bump version to 0.40.0 since I added a lot.

This also automagically moves saves from the old folder to the new folder, and deletes the old folder when done.

**Comment by AOx0** [comment]
Thanks for the pull request, and welcome :D 
I will be reviewing the changes anytime soon along with #45 and #50 and suggest any changes if needed.

**Comment by crispeeweevile** [comment]
After some minor testing, I've found that there seems to be a bug with the system. For unsigned 4 bit number the maximum is 15, but when trying to set a 4 bit bus pin the max it will let me is 8 this would make sense if it was signed, but it wont let me set it to negative numbers either

https://user-images.githubusercontent.com/92649061/213827592-f752b3e1-89c5-4b73-8e8c-3ed4c962e1aa.mp4

**Comment by pudy248** [comment]
Fixed. I misplaced a parentheses, `1 << (Pin.NumBits(wireType)) - 1` => `(1 << Pin.NumBits(wireType)) - 1` lol. Also, I was incorrectly accessing the current ChipEditor for wire deletion purposes, that's been fixed too.

**Comment by git123userhub** [comment]
cool, but can it store larger numbers without being offscreen?

**Comment by pudy248** [comment]
Yes, but the text quickly becomes too small to read on average displays. I'm not a UI designer, so I still haven't thought of a way to fix this. Ideas would be appreciated.

**Comment by pudy248** [comment]
image
Added a small commit for pin text formatting and overflow handling. Text is still a little bigger than it needs to be for my monitor, but I'm worried that if I make it any smaller it won't be readable for people with less than 1080p monitors. Currently it stays (mostly) within the pin even for the maximum possible input for 32bit busses.

**Comment by git123userhub** [comment]
perhaps, instead of having to make the integer inside the pin, you could make the input field (or plain label for output pins) somewhere in the context menu of the pin, as for directly seeing the value from the pin itself, you could truncate the integer instead, but im not really sure if this is a good idea.

**Comment by VitoBarra** [comment]
This feature is absolutely needed but I think that a better solution would be with a GUI that allows you to see and edit individual signals maybe also showing the encoded value. This could be done by extending the focus system and by adding the specific menu to the "menus" object in the "chip design" scene. In this way it ensures consistency with the pre-existent system and a better UX

photo_2023-01-26_12-26-50

this is a little mock-up of what I have in mind. obviously the number of pin should be changed programmatically

**Comment by git123userhub** [comment]
this pull request really should be closed by now.

**Comment by AOx0** [comment]
Why? I don't see no reason to close it @git123userhub.

**Comment by AOx0** [comment]
Okay, I was busy at that moment.
I get the idea now, it should be already merged. 

Maybe we should wait, see where the debate goes and come up with a better polished feature. Or merge immediately, compile and consider polishing in the future.

I don't know what is the correct answer, tho.

This is a community-guided project, so you guys decide how we should manage the fork, there's the discussion section where we can talk about the community priorities, philosophy, wanted features and goals, like with #57.

**Comment by pudy248** [comment]
I'm not particularly happy with the way the UX looks right now, but I'm a little limited in development time for the next week or two so I can't implement @VitoBarra's suggestion (which I think is a good one) right away. Since most users aren't using 32 bit pins anyway since there are no encoders/decoders on the main branch right now, and 32 bit pins are the only ones with major UX issues, it may be fine to release as is and add a v40.1 with improved UI later.

**Comment by pudy248** [comment]
With the above comment in mind, I decided to make 4, 8, and 16 bit busses look great and leave the issue of 32 bit for later. The text is small but is plenty readable in fullscreen on my 15" laptop monitor, so it should be good enough for the majority of users. Seeing the binary in the bus would still be a nice feature but having the ability to interface with busses as a user is urgently needed and even though the present solution isn't perfect, it's better than not having any way to edit busses.

**Comment by pudy248** [comment]
Unless there are some bugs I've failed to find, I would consider this PR ready to merge.

**Comment by git123userhub** [comment]
well, this cant really be merged since it doesnt have an approving review. 
guess we'll have to wait

**Comment by AOx0** [comment]
Yeah. Probably it will be batch merged along with other PRs to a separated dev branch. Then merged into main and released.

**Comment by pudy248** [comment]
I figured, the comment was directed at reviewers/mergers to let them know I won't be adding any more changes

**Comment by crispeeweevile** [comment]
I'll do a review soon. . . Just gotta finish up some stuff, I'm not too great with C# code though, so I'll basically just do a thorough bug test

**Review by crispeeweevile — CHANGES_REQUESTED** [review]
So far it's fine, but a couple of things:
-  Seeing as the 32 bit bus is now an option, I would like to be able to place up to 32 pins at once
- Most buses are unsigned; however, for some reason, the 32 bit bus is a signed bus, and you cannot access the negative bits. This actually might be an issue which maximum number sizes (maybe)
- One more thing, if you create a chip that contains chip(s) with no input connection (like 1hz clock), save it. once you save it edit another chip, and then try and edit the chip which contains a "bad chip" (one with no input) you will find that it causes a strange bug

If you need any extra information, let me know.

image

**Comment by pudy248** [comment]
The no input chip bug is known and not due to this PR. I don't know what's causing it and haven't had much time to look into it, but I'll fix it if I do find out. I can change all pins to use ulong instead of int for compatibility if we ever need 64 bit busses for some reason, or just make them uints.

Also, I've made some alterations to #45 and merged it with this branch on the hddPR branch in my repository but I'm not sure what best practice is for merging/PRing these sorts of changes since I haven't contributed to many open source repos before. In any case, if you all want to look at it, the branch should be stable and functioning.

**Comment by AOx0** [comment]
> Also, I've made some alterations to #45 and merged it with this branch on the hddPR branch in my repository but I'm not sure what best practice is for merging/PRing these sorts of changes since I haven't contributed to many open source repos before. In any case, if you all want to look at it, the branch should be stable and functioning.

A PR with both branches already merged would be nice.

**Comment by pudy248** [comment]
Closed as covered by #73

**Pull request closed without merging**
